# Generated by Django 5.0 on 2024-01-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
