# Generated by Django 5.0 on 2024-01-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_delete_usertorecieve'),
        ('wallets', '0002_wallet_bgn_wallet_btc_wallet_etc_wallet_eur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Will',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('transferData', models.DateTimeField()),
                ('amounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
                ('inheritor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.user')),
            ],
            options={
                'db_table': 'wills',
            },
        ),
    ]
