# Generated by Django 5.0 on 2024-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0002_remove_will_transferdata_will_transferdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='will',
            name='effectieImediate',
            field=models.BooleanField(default=False),
        ),
    ]
