# Generated by Django 5.0 on 2024-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0003_will_effectieimediate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='will',
            name='effectieImediate',
        ),
        migrations.AddField(
            model_name='will',
            name='effectiveImmediate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
