# Generated by Django 5.0 on 2024-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0004_remove_will_effectieimediate_will_effectiveimmediate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='will',
            name='transferDate',
            field=models.DateField(null=True),
        ),
    ]
