# Generated by Django 5.0 on 2024-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0005_alter_will_transferdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='will',
            name='willNumber',
            field=models.TextField(default=''),
        ),
    ]
