# Generated by Django 5.0 on 2024-01-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0006_will_willnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='will',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
