# Generated by Django 5.0 on 2024-01-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0007_will_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='will',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
