version: '3.9'

services:
  frontend:
    build: ./frontend
    command: ["sh", "-c", "npm run dev"]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"

volumes:
  data:
