# Generated by Django 5.0 on 2024-01-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_inboxentry_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxentry',
            name='wallet',
        ),
    ]
