# Generated by Django 5.0 on 2024-01-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_inboxentry_title'),
        ('users', '0014_user_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxentry',
            name='userFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user'),
        ),
    ]
