# Generated by Django 5.0 on 2024-01-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pin'),
        ('wallets', '0002_wallet_bgn_wallet_btc_wallet_etc_wallet_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet'),
        ),
    ]
