# Generated by Django 5.0 on 2024-01-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_wallet'),
        ('wallets', '0002_wallet_bgn_wallet_btc_wallet_etc_wallet_eur'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToRecieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
                ('transfer_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'transfer_users',
            },
        ),
    ]
