# Generated by Django 5.0 on 2024-01-13 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usertorecieve_transfer_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersToConfirm',
        ),
    ]
