# Generated by Django 5.0 on 2024-01-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
