# Generated by Django 5.0 on 2024-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bgn',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='wallet',
            name='btc',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='wallet',
            name='etc',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='wallet',
            name='eur',
            field=models.FloatField(default=50),
        ),
    ]
